# Site
repository: nhuhai
favicon: images/favicon.ico

# Personal info
name: Hai Nguyen
title: Senior Software Engineer
email: nhuhai.h.nguyen@gmail.com
# website: www.github.com/nhuhai

# Social links
github_username: nhuhai
linkedin_username: hainguyen90

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hai. I'm currently a Senior Software Engineer at Sony PlayStation, focusing on the front-end.
  After more than 5 years at PlayStation, I'm looking forward to my next journey on building software in other areas.
  I have extensive experiences in working with JavaScript and different front-end frameworks, especially React and React Native.
  In addition to the technical know-how, I'm also very keen on building applications that are fast and delightful.
  Having worked on different teams in an agile environment along with some remote working experience, I believe I'll be a good fit for this remote position.

  I am skilled in: 
  <mark>JavaSript</mark>
  <mark>ES6</mark>
  <mark>React</mark>
  <mark>React Native</mark>
  <mark>CSS</mark>
  <mark>SASS</mark>
  <mark>Redux</mark>
  <mark>GraphQL</mark>
  <mark>Jest</mark>
  <mark>Selenium</mark>
  <mark>NodeJS</mark>
  <mark>Flow</mark>
  <mark>Webpack</mark>
  <mark>Git</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in developing web apps and software engineering, some of my other interests and hobbies are:
   - Playing piano
   - Playing video games on my PS4
   - Hiking
   - Running

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
